---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Пользователь должен иметь возможность оформить заказ с переходом на страницу оплаты
  - Пользователь должен иметь возможность переключить язык интерфейса

non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию и быть доступен на различных устройствах
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен иметь локализацию (перевод) на русский и английский языки

implicit:
  - Корзина должна храниться в сессии браузера и сохранять выбранные товары при навигации
  - При фильтрации или поиске страницы не должны перезагружаться 
  - Страницы должны быть адаптивными и корректно отображаться на разных размерах экранов
  - Интерфейс должен быть интуитивно понятным и простым в использовании
